In [325]:
import pandas as pd

df= pd.read_csv('Airbnb_Open_Data.csv')

C:\Users\Megan\AppData\Local\Temp\ipykernel_18756\929202405.py:3: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df= pd.read_csv('Airbnb_Open_Data.csv')

In [326]:
print(df.head())

        id                                              NAME      host id  \
0  1001254                Clean & quiet apt home by the park  80014485718
1  1002102                             Skylit Midtown Castle  52335172823
2  1002403               THE VILLAGE OF HARLEM....NEW YORK !  78829239556
3  1002755                                               NaN  85098326012
4  1003689  Entire Apt: Spacious Studio/Loft by central park  92037596077

  host_identity_verified host name neighbourhood group neighbourhood  \
0            unconfirmed  Madaline            Brooklyn    Kensington
1               verified     Jenna           Manhattan       Midtown
2                    NaN     Elise           Manhattan        Harlem
3            unconfirmed     Garry            Brooklyn  Clinton Hill
4               verified    Lyndon           Manhattan   East Harlem

        lat      long        country  ... service fee minimum nights  \
0  40.64749 -73.97237  United States  ...       $193            10.0
1  40.75362 -73.98377  United States  ...        $28            30.0
2  40.80902 -73.94190  United States  ...       $124             3.0
3  40.68514 -73.95976  United States  ...        $74            30.0
4  40.79851 -73.94399  United States  ...        $41            10.0

  number of reviews last review  reviews per month review rate number  \
0               9.0  10/19/2021               0.21                4.0
1              45.0   5/21/2022               0.38                4.0
2               0.0         NaN                NaN                5.0
3             270.0    7/5/2019               4.64                4.0
4               9.0  11/19/2018               0.10                3.0

  calculated host listings count  availability 365  \
0                            6.0             286.0
1                            2.0             228.0
2                            1.0             352.0
3                            1.0             322.0
4                            1.0             289.0

                                         house_rules license
0  Clean up and treat the home the way you'd like...     NaN
1  Pet friendly but please confirm with me if the...     NaN
2  I encourage you to use my kitchen, cooking and...     NaN
3                                                NaN     NaN
4  Please no smoking in the house, porch or on th...     NaN

[5 rows x 26 columns]

In [327]:
print(df.describe)

<bound method NDFrame.describe of              id                                              NAME  \
0       1001254                Clean & quiet apt home by the park
1       1002102                             Skylit Midtown Castle
2       1002403               THE VILLAGE OF HARLEM....NEW YORK !
3       1002755                                               NaN
4       1003689  Entire Apt: Spacious Studio/Loft by central park
...         ...                                               ...
102594  6092437                        Spare room in Williamsburg
102595  6092990                     Best Location near Columbia U
102596  6093542                    Comfy, bright room in Brooklyn
102597  6094094                  Big Studio-One Stop from Midtown
102598  6094647                              585 sf Luxury Studio

            host id host_identity_verified    host name neighbourhood group  \
0       80014485718            unconfirmed     Madaline            Brooklyn
1       52335172823               verified        Jenna           Manhattan
2       78829239556                    NaN        Elise           Manhattan
3       85098326012            unconfirmed        Garry            Brooklyn
4       92037596077               verified       Lyndon           Manhattan
...             ...                    ...          ...                 ...
102594  12312296767               verified         Krik            Brooklyn
102595  77864383453            unconfirmed        Mifan           Manhattan
102596  69050334417            unconfirmed        Megan            Brooklyn
102597  11160591270            unconfirmed  Christopher              Queens
102598  68170633372            unconfirmed      Rebecca           Manhattan

              neighbourhood       lat      long        country  ...  \
0                Kensington  40.64749 -73.97237  United States  ...
1                   Midtown  40.75362 -73.98377  United States  ...
2                    Harlem  40.80902 -73.94190  United States  ...
3              Clinton Hill  40.68514 -73.95976  United States  ...
4               East Harlem  40.79851 -73.94399  United States  ...
...                     ...       ...       ...            ...  ...
102594         Williamsburg  40.70862 -73.94651  United States  ...
102595  Morningside Heights  40.80460 -73.96545  United States  ...
102596           Park Slope  40.67505 -73.98045  United States  ...
102597     Long Island City  40.74989 -73.93777  United States  ...
102598      Upper West Side  40.76807 -73.98342  United States  ...

       service fee minimum nights number of reviews last review  \
0            $193            10.0               9.0  10/19/2021
1             $28            30.0              45.0   5/21/2022
2            $124             3.0               0.0         NaN
3             $74            30.0             270.0    7/5/2019
4             $41            10.0               9.0  11/19/2018
...            ...            ...               ...         ...
102594       $169             1.0               0.0         NaN
102595       $167             1.0               1.0    7/6/2015
102596       $198             3.0               0.0         NaN
102597       $109             2.0               5.0  10/11/2015
102598       $206             1.0               0.0         NaN

        reviews per month review rate number calculated host listings count  \
0                    0.21                4.0                            6.0
1                    0.38                4.0                            2.0
2                     NaN                5.0                            1.0
3                    4.64                4.0                            1.0
4                    0.10                3.0                            1.0
...                   ...                ...                            ...
102594                NaN                3.0                            1.0
102595               0.02                2.0                            2.0
102596                NaN                5.0                            1.0
102597               0.10                3.0                            1.0
102598                NaN                3.0                            1.0

        availability 365                                        house_rules  \
0                  286.0  Clean up and treat the home the way you'd like...
1                  228.0  Pet friendly but please confirm with me if the...
2                  352.0  I encourage you to use my kitchen, cooking and...
3                  322.0                                                NaN
4                  289.0  Please no smoking in the house, porch or on th...
...                  ...                                                ...
102594             227.0  No Smoking No Parties or Events of any kind Pl...
102595             395.0  House rules: Guests agree to the following ter...
102596             342.0                                                NaN
102597             386.0                                                NaN
102598              69.0                                                NaN

       license
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
102594     NaN
102595     NaN
102596     NaN
102597     NaN
102598     NaN

[102599 rows x 26 columns]>

In [328]:
df.info()
print(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  object
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host name                       102193 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room type                       102599 non-null  object
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  object
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
 25  license                         2 non-null       object
dtypes: float64(9), int64(2), object(15)
memory usage: 20.4+ MB
             id                                              NAME  \
0       1001254                Clean & quiet apt home by the park
1       1002102                             Skylit Midtown Castle
2       1002403               THE VILLAGE OF HARLEM....NEW YORK !
3       1002755                                               NaN
4       1003689  Entire Apt: Spacious Studio/Loft by central park
...         ...                                               ...
102594  6092437                        Spare room in Williamsburg
102595  6092990                     Best Location near Columbia U
102596  6093542                    Comfy, bright room in Brooklyn
102597  6094094                  Big Studio-One Stop from Midtown
102598  6094647                              585 sf Luxury Studio

            host id host_identity_verified    host name neighbourhood group  \
0       80014485718            unconfirmed     Madaline            Brooklyn
1       52335172823               verified        Jenna           Manhattan
2       78829239556                    NaN        Elise           Manhattan
3       85098326012            unconfirmed        Garry            Brooklyn
4       92037596077               verified       Lyndon           Manhattan
...             ...                    ...          ...                 ...
102594  12312296767               verified         Krik            Brooklyn
102595  77864383453            unconfirmed        Mifan           Manhattan
102596  69050334417            unconfirmed        Megan            Brooklyn
102597  11160591270            unconfirmed  Christopher              Queens
102598  68170633372            unconfirmed      Rebecca           Manhattan

              neighbourhood       lat      long        country  ...  \
0                Kensington  40.64749 -73.97237  United States  ...
1                   Midtown  40.75362 -73.98377  United States  ...
2                    Harlem  40.80902 -73.94190  United States  ...
3              Clinton Hill  40.68514 -73.95976  United States  ...
4               East Harlem  40.79851 -73.94399  United States  ...
...                     ...       ...       ...            ...  ...
102594         Williamsburg  40.70862 -73.94651  United States  ...
102595  Morningside Heights  40.80460 -73.96545  United States  ...
102596           Park Slope  40.67505 -73.98045  United States  ...
102597     Long Island City  40.74989 -73.93777  United States  ...
102598      Upper West Side  40.76807 -73.98342  United States  ...

       service fee minimum nights number of reviews last review  \
0            $193            10.0               9.0  10/19/2021
1             $28            30.0              45.0   5/21/2022
2            $124             3.0               0.0         NaN
3             $74            30.0             270.0    7/5/2019
4             $41            10.0               9.0  11/19/2018
...            ...            ...               ...         ...
102594       $169             1.0               0.0         NaN
102595       $167             1.0               1.0    7/6/2015
102596       $198             3.0               0.0         NaN
102597       $109             2.0               5.0  10/11/2015
102598       $206             1.0               0.0         NaN

        reviews per month review rate number calculated host listings count  \
0                    0.21                4.0                            6.0
1                    0.38                4.0                            2.0
2                     NaN                5.0                            1.0
3                    4.64                4.0                            1.0
4                    0.10                3.0                            1.0
...                   ...                ...                            ...
102594                NaN                3.0                            1.0
102595               0.02                2.0                            2.0
102596                NaN                5.0                            1.0
102597               0.10                3.0                            1.0
102598                NaN                3.0                            1.0

        availability 365                                        house_rules  \
0                  286.0  Clean up and treat the home the way you'd like...
1                  228.0  Pet friendly but please confirm with me if the...
2                  352.0  I encourage you to use my kitchen, cooking and...
3                  322.0                                                NaN
4                  289.0  Please no smoking in the house, porch or on th...
...                  ...                                                ...
102594             227.0  No Smoking No Parties or Events of any kind Pl...
102595             395.0  House rules: Guests agree to the following ter...
102596             342.0                                                NaN
102597             386.0                                                NaN
102598              69.0                                                NaN

       license
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
102594     NaN
102595     NaN
102596     NaN
102597     NaN
102598     NaN

[102599 rows x 26 columns]

In [329]:
print(df.isnull().sum())

id                                     0
NAME                                 250
host id                                0
host_identity_verified               289
host name                            406
neighbourhood group                   29
neighbourhood                         16
lat                                    8
long                                   8
country                              532
country code                         131
instant_bookable                     105
cancellation_policy                   76
room type                              0
Construction year                    214
price                                247
service fee                          273
minimum nights                       409
number of reviews                    183
last review                        15893
reviews per month                  15879
review rate number                   326
calculated host listings count       319
availability 365                     448
house_rules                        52131
license                           102597
dtype: int64

In [330]:
#dropeamos la columna "license" ya que tiene muchos valores nulos y solo dos valores no nulos (no aporta informacion)
df.drop('license', axis=1, inplace=True)
print(df.head())

        id                                              NAME      host id  \
0  1001254                Clean & quiet apt home by the park  80014485718
1  1002102                             Skylit Midtown Castle  52335172823
2  1002403               THE VILLAGE OF HARLEM....NEW YORK !  78829239556
3  1002755                                               NaN  85098326012
4  1003689  Entire Apt: Spacious Studio/Loft by central park  92037596077

  host_identity_verified host name neighbourhood group neighbourhood  \
0            unconfirmed  Madaline            Brooklyn    Kensington
1               verified     Jenna           Manhattan       Midtown
2                    NaN     Elise           Manhattan        Harlem
3            unconfirmed     Garry            Brooklyn  Clinton Hill
4               verified    Lyndon           Manhattan   East Harlem

        lat      long        country  ...  price service fee minimum nights  \
0  40.64749 -73.97237  United States  ...  $966        $193            10.0
1  40.75362 -73.98377  United States  ...  $142         $28            30.0
2  40.80902 -73.94190  United States  ...  $620        $124             3.0
3  40.68514 -73.95976  United States  ...  $368         $74            30.0
4  40.79851 -73.94399  United States  ...  $204         $41            10.0

  number of reviews  last review reviews per month review rate number  \
0               9.0   10/19/2021              0.21                4.0
1              45.0    5/21/2022              0.38                4.0
2               0.0          NaN               NaN                5.0
3             270.0     7/5/2019              4.64                4.0
4               9.0   11/19/2018              0.10                3.0

   calculated host listings count  availability 365  \
0                             6.0             286.0
1                             2.0             228.0
2                             1.0             352.0
3                             1.0             322.0
4                             1.0             289.0

                                         house_rules
0  Clean up and treat the home the way you'd like...
1  Pet friendly but please confirm with me if the...
2  I encourage you to use my kitchen, cooking and...
3                                                NaN
4  Please no smoking in the house, porch or on th...

[5 rows x 25 columns]

In [331]:
df.drop('country code', axis=1, inplace=True)
print(df.head())

        id                                              NAME      host id  \
0  1001254                Clean & quiet apt home by the park  80014485718
1  1002102                             Skylit Midtown Castle  52335172823
2  1002403               THE VILLAGE OF HARLEM....NEW YORK !  78829239556
3  1002755                                               NaN  85098326012
4  1003689  Entire Apt: Spacious Studio/Loft by central park  92037596077

  host_identity_verified host name neighbourhood group neighbourhood  \
0            unconfirmed  Madaline            Brooklyn    Kensington
1               verified     Jenna           Manhattan       Midtown
2                    NaN     Elise           Manhattan        Harlem
3            unconfirmed     Garry            Brooklyn  Clinton Hill
4               verified    Lyndon           Manhattan   East Harlem

        lat      long        country  ...  price service fee minimum nights  \
0  40.64749 -73.97237  United States  ...  $966        $193            10.0
1  40.75362 -73.98377  United States  ...  $142         $28            30.0
2  40.80902 -73.94190  United States  ...  $620        $124             3.0
3  40.68514 -73.95976  United States  ...  $368         $74            30.0
4  40.79851 -73.94399  United States  ...  $204         $41            10.0

   number of reviews last review reviews per month  review rate number  \
0                9.0  10/19/2021              0.21                 4.0
1               45.0   5/21/2022              0.38                 4.0
2                0.0         NaN               NaN                 5.0
3              270.0    7/5/2019              4.64                 4.0
4                9.0  11/19/2018              0.10                 3.0

   calculated host listings count availability 365  \
0                             6.0            286.0
1                             2.0            228.0
2                             1.0            352.0
3                             1.0            322.0
4                             1.0            289.0

                                         house_rules
0  Clean up and treat the home the way you'd like...
1  Pet friendly but please confirm with me if the...
2  I encourage you to use my kitchen, cooking and...
3                                                NaN
4  Please no smoking in the house, porch or on th...

[5 rows x 24 columns]

In [332]:
df["service fee"] = df["service fee"].str.replace("$", "").str.replace(",", "").astype(float)
df["price"] = df["price"].str.replace("$", "").str.replace(",", "").astype(float)

In [333]:
#LLenando valores nulos
df['house_rules'].fillna('None', inplace=True)
df['country'].fillna('United States', inplace=True)
df['lat'].fillna(0, inplace=True)
df['long'].fillna(0, inplace=True)
df['host_identity_verified'].fillna('unconfirmed', inplace=True)
df['instant_bookable'].fillna('FALSE', inplace=True)
df['number of reviews'].fillna(0, inplace=True)
df['minimum nights'].fillna(1, inplace=True)
df['availability 365'].fillna(0, inplace=True)
df['price'].fillna(0, inplace=True)
df['service fee'].fillna(0, inplace=True)
df['reviews per month'].fillna(0, inplace=True)
df['calculated host listings count'].fillna(0, inplace=True)
df['review rate number'].fillna(0, inplace=True)
df.fillna('None', inplace=True)

print(df.isnull().sum())

id                                0
NAME                              0
host id                           0
host_identity_verified            0
host name                         0
neighbourhood group               0
neighbourhood                     0
lat                               0
long                              0
country                           0
instant_bookable                  0
cancellation_policy               0
room type                         0
Construction year                 0
price                             0
service fee                       0
minimum nights                    0
number of reviews                 0
last review                       0
reviews per month                 0
review rate number                0
calculated host listings count    0
availability 365                  0
house_rules                       0
dtype: int64

C:\Users\Megan\AppData\Local\Temp\ipykernel_18756\3694421123.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['house_rules'].fillna('None', inplace=True)
C:\Users\Megan\AppData\Local\Temp\ipykernel_18756\3694421123.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['country'].fillna('United States', inplace=True)
C:\Users\Megan\AppData\Local\Temp\ipykernel_18756\3694421123.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['lat'].fillna(0, inplace=True)
C:\Users\Megan\AppData\Local\Temp\ipykernel_18756\3694421123.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['long'].fillna(0, inplace=True)
C:\Users\Megan\AppData\Local\Temp\ipykernel_18756\3694421123.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['host_identity_verified'].fillna('unconfirmed', inplace=True)
C:\Users\Megan\AppData\Local\Temp\ipykernel_18756\3694421123.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['instant_bookable'].fillna('FALSE', inplace=True)
C:\Users\Megan\AppData\Local\Temp\ipykernel_18756\3694421123.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['number of reviews'].fillna(0, inplace=True)
C:\Users\Megan\AppData\Local\Temp\ipykernel_18756\3694421123.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['minimum nights'].fillna(1, inplace=True)
C:\Users\Megan\AppData\Local\Temp\ipykernel_18756\3694421123.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['availability 365'].fillna(0, inplace=True)
C:\Users\Megan\AppData\Local\Temp\ipykernel_18756\3694421123.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['price'].fillna(0, inplace=True)
C:\Users\Megan\AppData\Local\Temp\ipykernel_18756\3694421123.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['service fee'].fillna(0, inplace=True)
C:\Users\Megan\AppData\Local\Temp\ipykernel_18756\3694421123.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['reviews per month'].fillna(0, inplace=True)
C:\Users\Megan\AppData\Local\Temp\ipykernel_18756\3694421123.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['calculated host listings count'].fillna(0, inplace=True)
C:\Users\Megan\AppData\Local\Temp\ipykernel_18756\3694421123.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['review rate number'].fillna(0, inplace=True)
C:\Users\Megan\AppData\Local\Temp\ipykernel_18756\3694421123.py:16: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'None' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.fillna('None', inplace=True)

In [334]:
#separando las fechas en año y mes
df['last review'] = pd.to_datetime(df['last review'], errors='coerce')

df['year_review'] = df['last review'].dt.year
df['month_review'] = df['last review'].dt.month

df['year_review'] = df['year_review'].fillna(0).astype(int)
df['month_review'] = df['month_review'].fillna(0).astype(int)

print(df[['last review', 'year_review', 'month_review']].head())

  last review  year_review  month_review
0  2021-10-19         2021            10
1  2022-05-21         2022             5
2         NaT            0             0
3  2019-07-05         2019             7
4  2018-11-19         2018            11

In [335]:
df.drop('last review', axis=1, inplace=True)

In [336]:
for column in df.columns:
    print(f"Unique values in '{column}':")
    print(df[column].unique())
    print()

Unique values in 'id':
[ 1001254  1002102  1002403 ... 57366313 57366865 57367417]

Unique values in 'NAME':
['Clean & quiet apt home by the park' 'Skylit Midtown Castle'
 'THE VILLAGE OF HARLEM....NEW YORK !' ...
 'Elmhurst 1st Fl Rightl Bedroom'
 'Elmhurst 1st Floor BR w/ Pvt. Bath&Balcony'
 'Parisian Style Apartment in Heart of Brooklyn']

Unique values in 'host id':
[80014485718 52335172823 78829239556 ... 23801060917 15593031571
 93578954226]

Unique values in 'host_identity_verified':
['unconfirmed' 'verified']

Unique values in 'host name':
['Madaline' 'Jenna' 'Elise' ... 'Anna B' 'Natalie And Dan' 'Apostle John']

Unique values in 'neighbourhood group':
['Brooklyn' 'Manhattan' 'brookln' 'manhatan' 'Queens' 'None'
 'Staten Island' 'Bronx']

Unique values in 'neighbourhood':
['Kensington' 'Midtown' 'Harlem' 'Clinton Hill' 'East Harlem'
 'Murray Hill' 'Bedford-Stuyvesant' "Hell's Kitchen" 'Upper West Side'
 'Chinatown' 'South Slope' 'West Village' 'Williamsburg' 'Fort Greene'
 'Chelsea' 'Crown Heights' 'Park Slope' 'Windsor Terrace' 'Inwood'
 'East Village' 'Greenpoint' 'Bushwick' 'Flatbush' 'Lower East Side'
 'Prospect-Lefferts Gardens' 'Long Island City' 'Kips Bay' 'SoHo'
 'Upper East Side' 'Prospect Heights' 'Washington Heights' 'Woodside'
 'Brooklyn Heights' 'Carroll Gardens' 'Gowanus' 'Flatlands' 'Cobble Hill'
 'Flushing' 'Boerum Hill' 'Sunnyside' 'DUMBO' 'St. George' 'Highbridge'
 'Financial District' 'Ridgewood' 'Morningside Heights' 'Jamaica'
 'Middle Village' 'NoHo' 'Ditmars Steinway' 'Flatiron District'
 'Roosevelt Island' 'Greenwich Village' 'Little Italy' 'East Flatbush'
 'Tompkinsville' 'Astoria' 'Clason Point' 'Eastchester' 'Kingsbridge'
 'Two Bridges' 'Queens Village' 'Rockaway Beach' 'Forest Hills' 'Nolita'
 'Woodlawn' 'University Heights' 'Gravesend' 'Gramercy' 'Allerton' 'None'
 'East New York' 'Theater District' 'Concourse Village' 'Sheepshead Bay'
 'Emerson Hill' 'Fort Hamilton' 'Bensonhurst' 'Tribeca' 'Shore Acres'
 'Sunset Park' 'Concourse' 'Elmhurst' 'Brighton Beach' 'Jackson Heights'
 'Cypress Hills' 'St. Albans' 'Arrochar' 'Rego Park' 'Wakefield' 'Clifton'
 'Bay Ridge' 'Graniteville' 'Spuyten Duyvil' 'Stapleton' 'Briarwood'
 'Ozone Park' 'Columbia St' 'Vinegar Hill' 'Mott Haven' 'Longwood'
 'Canarsie' 'Battery Park City' 'Civic Center' 'East Elmhurst'
 'New Springville' 'Morris Heights' 'Arverne' 'Cambria Heights'
 'Tottenville' 'Mariners Harbor' 'Concord' 'Borough Park' 'Bayside'
 'Downtown Brooklyn' 'Port Morris' 'Fieldston' 'Kew Gardens' 'Midwood'
 'College Point' 'Mount Eden' 'City Island' 'Glendale' 'Port Richmond'
 'Red Hook' 'Richmond Hill' 'Bellerose' 'Maspeth' 'Williamsbridge'
 'Soundview' 'Woodhaven' 'Woodrow' 'Co-op City' 'Stuyvesant Town'
 'Parkchester' 'North Riverdale' 'Dyker Heights' 'Bronxdale' 'Sea Gate'
 'Riverdale' 'Kew Gardens Hills' 'Bay Terrace' 'Norwood'
 'Claremont Village' 'Whitestone' 'Fordham' 'Bayswater' 'Navy Yard'
 'Brownsville' 'Eltingville' 'Fresh Meadows' 'Mount Hope'
 'Lighthouse Hill' 'Springfield Gardens' 'Howard Beach' 'Belle Harbor'
 'Jamaica Estates' 'Van Nest' 'Morris Park' 'West Brighton' 'Far Rockaway'
 'South Ozone Park' 'Tremont' 'Corona' 'Great Kills' 'Manhattan Beach'
 'Marble Hill' 'Dongan Hills' 'Castleton Corners' 'East Morrisania'
 'Hunts Point' 'Neponsit' 'Pelham Bay' 'Randall Manor' 'Throgs Neck'
 'Todt Hill' 'West Farms' 'Silver Lake' 'Morrisania' 'Laurelton'
 'Grymes Hill' 'Holliswood' 'Pelham Gardens' 'Belmont' 'Rosedale'
 'Edgemere' 'New Brighton' 'Midland Beach' 'Baychester' 'Melrose'
 'Bergen Beach' 'Richmondtown' 'Howland Hook' 'Schuylerville'
 'Coney Island' 'New Dorp Beach' "Prince's Bay" 'South Beach' 'Bath Beach'
 'Jamaica Hills' 'Oakwood' 'Castle Hill' 'Hollis' 'Douglaston' 'Huguenot'
 'Olinville' 'Edenwald' 'Grant City' 'Westerleigh'
 'Bay Terrace, Staten Island' 'Westchester Square' 'Little Neck'
 'Fort Wadsworth' 'Rosebank' 'Unionport' 'Mill Basin' 'Arden Heights'
 "Bull's Head" 'New Dorp' 'Rossville' 'Breezy Point' 'Willowbrook'
 'Glen Oaks' 'Gerritsen Beach' 'Chelsea, Staten Island']

Unique values in 'lat':
[40.64749 40.75362 40.80902 ... 40.63724 40.7669  40.84753]

Unique values in 'long':
[-73.97237 -73.98377 -73.9419  ... -73.86641 -73.89963 -73.89887]

Unique values in 'country':
['United States']

Unique values in 'instant_bookable':
[False True 'FALSE']

Unique values in 'cancellation_policy':
['strict' 'moderate' 'flexible' 'None']

Unique values in 'room type':
['Private room' 'Entire home/apt' 'Shared room' 'Hotel room']

Unique values in 'Construction year':
[2020.0 2007.0 2005.0 2009.0 2013.0 2015.0 2004.0 2008.0 2010.0 2019.0
 2018.0 2006.0 2016.0 2017.0 2021.0 2003.0 2011.0 2012.0 2022.0 2014.0
 'None']

Unique values in 'price':
[ 966.  142.  620. ... 1184.  905.  309.]

Unique values in 'service fee':
[193.  28. 124.  74.  41. 115.  14. 212. 204.  58.  64. 121. 143. 116.
  30.   0.  56.  95.  27. 210. 163. 235. 106.  55.  42.  86. 133. 154.
 102. 172. 109.  38. 222. 219. 202. 113. 137. 171.  12.  87. 183.  92.
  73. 146. 180.  67.  51. 181.  88. 205. 132.  59. 156. 131.  61. 165.
 129. 207.  17.  63. 147. 105.  48. 114.  80.  23.  11. 149. 213. 211.
 182. 117.  39.  25. 216.  53.  10. 118.  72.  76.  69.  32. 148. 101.
 177.  49. 100. 168.  13. 152. 126. 135.  46. 231.  91. 199. 158. 221.
 189.  90. 186.  66. 225. 220.  19. 238. 119.  98.  34. 227. 162. 203.
  93. 153.  71.  77. 190.  75. 185.  97.  35.  37.  82. 120.  21. 145.
  65. 144. 108. 194.  16. 217. 188.  81. 139.  22. 187. 150.  50. 176.
 151.  26.  89. 218. 104.  44.  79. 240. 175. 192. 215. 191.  94. 206.
 157. 159. 233.  15. 229. 179.  85. 136. 170. 201. 141. 123.  36. 130.
 198.  54. 122. 184. 208. 140.  68. 196.  70. 228. 209. 230. 134.  20.
 110. 234. 107. 138.  45.  24.  31.  29. 232.  47. 239. 161. 200.  33.
 103.  83. 128. 166. 125.  43.  18. 167. 174. 236. 111. 142. 223. 169.
 178. 195.  40.  52.  96. 224. 197. 164. 127.  62.  99.  84. 237. 155.
  57. 226. 160. 173.  60. 214.  78. 112.]

Unique values in 'minimum nights':
[ 1.000e+01  3.000e+01  3.000e+00  4.500e+01  2.000e+00  1.000e+00
  5.000e+00  4.000e+00  9.000e+01  7.000e+00  1.400e+01  6.000e+01
  1.800e+02  9.000e+00  3.100e+01  6.000e+00  1.500e+01  2.900e+01
  8.000e+00  4.700e+01  8.100e+01  1.440e+02  3.710e+02  1.490e+02
  2.730e+02  1.310e+02  2.750e+02  3.230e+02  5.900e+01  9.900e+01
  2.680e+02 -1.000e+01  1.890e+02  3.400e+02  1.280e+02  3.500e+02
  1.660e+02  1.100e+02  5.700e+01  1.420e+02  3.660e+02  2.800e+01
  2.000e+02  5.000e+01  3.990e+02  1.700e+01  1.100e+01  4.520e+02
  2.500e+01  1.300e+01  3.455e+03 -5.000e+00  2.100e+01  2.700e+01
  1.800e+01  3.650e+02 -1.000e+00  2.000e+01 -1.200e+01  4.000e+01
  4.400e+01  3.980e+02 -2.000e+00  6.500e+01 -3.000e+00  5.500e+01
  1.200e+02  1.220e+02  1.900e+01  2.400e+02  8.800e+01  1.150e+02
  1.500e+02  3.700e+02  1.600e+01  8.000e+01  1.810e+02  2.600e+01
  2.650e+02  3.000e+02  1.850e+02  3.600e+02  5.600e+01  1.200e+01
  7.000e+01  3.900e+01  2.400e+01  3.200e+01  1.000e+03  2.700e+02
  2.200e+01  7.500e+01  2.500e+02  6.200e+01  2.300e+01  1.250e+03
  3.640e+02  7.400e+01  1.980e+02  1.000e+02  5.000e+02  4.300e+01
  3.500e+01  9.100e+01  4.800e+02  5.300e+01  1.600e+02  9.990e+02
  1.860e+02  6.800e+01  9.300e+01  8.700e+01  1.830e+02  2.990e+02
  1.750e+02  9.800e+01  1.330e+02  3.540e+02  4.200e+01  3.300e+01
  3.700e+01  2.250e+02  4.000e+02  1.050e+02  1.840e+02  1.530e+02
  1.340e+02  2.220e+02  5.800e+01  2.100e+02  1.820e+02  9.540e+02
  5.645e+03  2.645e+03 -1.223e+03 -3.650e+02 -2.000e+02  1.140e+02
  8.500e+01  3.600e+01  4.800e+01  1.550e+02  3.070e+02  1.290e+02
  1.450e+02  6.400e+01  3.330e+02  1.190e+02 -1.250e+02  1.250e+02
  3.400e+01  4.580e+02  8.250e+02]

Unique values in 'number of reviews':
[9.000e+00 4.500e+01 0.000e+00 2.700e+02 7.400e+01 4.900e+01 4.300e+02
 1.180e+02 1.600e+02 5.300e+01 1.880e+02 1.670e+02 1.130e+02 2.700e+01
 1.480e+02 1.980e+02 2.600e+02 1.300e+02 3.900e+01 7.100e+01 8.800e+01
 1.900e+01 5.800e+01 1.080e+02 2.900e+01 2.420e+02 1.970e+02 2.730e+02
 1.680e+02 2.310e+02 2.140e+02 2.450e+02 1.500e+01 2.500e+01 8.100e+01
 9.700e+01 1.100e+01 2.480e+02 6.100e+01 1.350e+02 1.120e+02 7.300e+01
 8.200e+01 3.280e+02 1.050e+02 2.890e+02 1.380e+02 2.100e+01 4.200e+01
 5.000e+00 6.600e+01 1.430e+02 1.910e+02 4.000e+00 3.380e+02 1.060e+02
 1.900e+02 2.300e+01 1.420e+02 5.400e+01 7.000e+01 1.600e+01 9.400e+01
 1.940e+02 2.000e+00 1.740e+02 2.400e+01 1.660e+02 1.000e+00 3.000e+01
 1.390e+02 2.330e+02 6.800e+01 4.600e+01 3.350e+02 1.620e+02 1.700e+02
 3.340e+02 1.200e+01 4.670e+02 7.000e+00 3.800e+01 3.240e+02 1.150e+02
 3.540e+02 1.950e+02 1.300e+01 3.600e+01 6.300e+01 1.550e+02 1.930e+02
 3.200e+01 5.000e+01 2.600e+01 4.260e+02 2.270e+02 8.400e+01 1.000e+01
 1.240e+02 2.400e+02 2.000e+02 7.900e+01 3.400e+01 1.340e+02 1.260e+02
 2.340e+02 2.020e+02 2.800e+01 3.090e+02 1.400e+01 8.000e+01 2.940e+02
 1.500e+02 4.700e+01 2.190e+02 1.140e+02 2.130e+02 8.600e+01 1.800e+01
 2.060e+02 1.220e+02 3.300e+01 5.200e+01 5.100e+01 1.990e+02 3.000e+00
 4.100e+01 1.090e+02 1.510e+02 2.850e+02 3.750e+02 6.000e+00 3.580e+02
 2.260e+02 1.040e+02 2.040e+02 2.530e+02 1.290e+02 3.700e+01 6.900e+01
 1.920e+02 1.700e+01 2.220e+02 2.050e+02 4.580e+02 1.830e+02 1.890e+02
 1.270e+02 3.500e+01 1.710e+02 9.200e+01 2.380e+02 5.600e+01 1.110e+02
 1.470e+02 1.770e+02 1.850e+02 6.200e+01 1.810e+02 3.330e+02 4.410e+02
 2.790e+02 2.030e+02 2.100e+02 6.400e+01 1.320e+02 2.000e+01 6.700e+01
 1.870e+02 2.200e+01 9.300e+01 4.800e+01 1.200e+02 4.300e+01 5.900e+01
 3.100e+01 2.200e+02 2.860e+02 3.980e+02 7.600e+01 1.820e+02 8.000e+00
 2.280e+02 3.880e+02 2.230e+02 2.180e+02 7.500e+01 3.700e+02 1.310e+02
 1.360e+02 9.800e+01 3.800e+02 1.630e+02 2.470e+02 1.160e+02 3.200e+02
 2.250e+02 9.500e+01 4.030e+02 1.750e+02 2.630e+02 2.320e+02 7.200e+01
 4.140e+02 1.190e+02 1.170e+02 3.850e+02 1.030e+02 2.800e+02 5.700e+01
 4.800e+02 1.010e+02 8.700e+01 2.410e+02 9.000e+01 9.900e+01 2.710e+02
 8.900e+01 1.790e+02 4.010e+02 8.300e+01 2.110e+02 2.950e+02 2.070e+02
 1.720e+02 3.300e+02 1.230e+02 5.500e+01 2.580e+02 1.280e+02 1.520e+02
 1.540e+02 1.640e+02 2.780e+02 2.350e+02 3.050e+02 1.020e+02 6.500e+01
 4.000e+01 1.000e+02 1.250e+02 2.290e+02 6.000e+01 1.070e+02 1.760e+02
 1.780e+02 2.160e+02 3.140e+02 1.530e+02 1.100e+02 2.440e+02 2.080e+02
 1.210e+02 1.570e+02 2.090e+02 4.400e+01 1.580e+02 2.360e+02 2.150e+02
 7.800e+01 2.970e+02 7.700e+01 2.650e+02 1.560e+02 2.720e+02 2.680e+02
 1.330e+02 1.650e+02 2.690e+02 2.430e+02 1.370e+02 1.450e+02 3.390e+02
 4.540e+02 2.300e+02 1.440e+02 4.390e+02 2.610e+02 3.190e+02 1.840e+02
 4.510e+02 1.690e+02 2.660e+02 2.510e+02 1.410e+02 3.040e+02 4.740e+02
 8.500e+01 2.210e+02 2.010e+02 3.210e+02 2.500e+02 1.490e+02 2.540e+02
 1.610e+02 3.230e+02 3.470e+02 2.960e+02 9.600e+01 1.730e+02 2.390e+02
 4.040e+02 3.260e+02 3.630e+02 1.460e+02 3.270e+02 2.370e+02 3.530e+02
 9.100e+01 3.020e+02 2.760e+02 1.860e+02 3.220e+02 2.670e+02 5.400e+02
 2.240e+02 2.910e+02 3.150e+02 3.130e+02 5.940e+02 5.970e+02 6.070e+02
 2.870e+02 1.590e+02 3.950e+02 4.470e+02 2.810e+02 3.560e+02 3.600e+02
 3.490e+02 2.460e+02 3.080e+02 2.920e+02 1.400e+02 2.840e+02 3.740e+02
 1.960e+02 2.120e+02 2.740e+02 3.400e+02 3.860e+02 3.360e+02 2.490e+02
 2.750e+02 2.590e+02 2.520e+02 2.980e+02 2.880e+02 2.550e+02 3.650e+02
 2.570e+02 2.170e+02 4.880e+02 3.320e+02 1.800e+02 2.770e+02 3.890e+02
 3.720e+02 2.990e+02 3.940e+02 3.570e+02 3.500e+02 3.520e+02 3.510e+02
 2.620e+02 3.180e+02 3.070e+02 3.250e+02 2.820e+02 3.960e+02 4.660e+02
 3.970e+02 2.900e+02 4.480e+02 4.240e+02 4.080e+02 5.430e+02 2.640e+02
 6.290e+02 5.760e+02 2.560e+02 4.590e+02 4.120e+02 3.780e+02 4.110e+02
 4.340e+02 5.100e+02 3.060e+02 3.920e+02 4.170e+02 3.680e+02 4.360e+02
 3.100e+02 3.410e+02 3.480e+02 7.760e+02 8.490e+02 6.180e+02 4.850e+02
 5.500e+02 3.640e+02 4.150e+02 4.430e+02 3.770e+02 3.790e+02 3.290e+02
 4.750e+02 9.660e+02 7.970e+02 5.920e+02 5.670e+02 6.480e+02 3.670e+02
 4.830e+02 3.460e+02 4.060e+02 4.690e+02 3.420e+02 3.110e+02 3.450e+02
 6.380e+02 3.620e+02 5.600e+02 6.980e+02 3.990e+02 4.320e+02 3.440e+02
 4.490e+02 5.420e+02 3.710e+02 2.930e+02 3.610e+02 4.700e+02 4.730e+02
 3.870e+02 4.960e+02 4.380e+02 4.130e+02 1.024e+03 3.010e+02 3.030e+02
 4.550e+02 8.840e+02 4.180e+02 5.200e+02 5.660e+02 2.830e+02 4.400e+02
 3.120e+02 4.200e+02 4.330e+02 3.370e+02 4.500e+02 5.830e+02 3.160e+02
 4.910e+02 3.660e+02 3.430e+02 6.790e+02 5.630e+02 3.170e+02 3.730e+02
 5.560e+02 4.290e+02 3.310e+02 4.680e+02 7.380e+02 4.770e+02 4.840e+02
 5.010e+02 4.210e+02 1.010e+03 4.460e+02 4.900e+02 4.000e+02 3.000e+02]

Unique values in 'reviews per month':
[ 0.21  0.38  0.   ...  7.73 24.49 33.08]

Unique values in 'review rate number':
[4. 5. 3. 0. 2. 1.]

Unique values in 'calculated host listings count':
[  6.   2.   1.   4.   3.   0.   5.   7.  13.  28.  11.   8.   9.  52.
  18.  15.  19.  10.  39.  26.  29.  12.  21.  96.  14.  34.  43. 121.
  37.  49.  31.  91.  16.  87.  33.  23.  50.  20.  25. 232.  17.  47.
 103.  65.  30.  27. 327.  32.  45.  53. 208. 171.  44.  48. 108.  51.
 161. 152.  83.  24.  22. 126.  54.  66.  59.  62. 102. 186. 125.  55.
  63.  67.  58.  56.  80.  46. 218.  86. 332.]

Unique values in 'availability 365':
[ 2.860e+02  2.280e+02  3.520e+02  3.220e+02  2.890e+02  3.740e+02
  2.240e+02  2.190e+02  1.800e+02  3.750e+02  1.000e+00  1.630e+02
  2.580e+02  4.700e+01  6.800e+01  1.000e+02  1.970e+02  9.600e+01
  3.250e+02  3.450e+02  3.470e+02  1.930e+02  5.400e+01  9.000e+00
  3.440e+02  3.720e+02  1.030e+02  1.720e+02  5.600e+01  1.050e+02
  1.690e+02  3.830e+02  4.110e+02  7.600e+01  4.160e+02  2.940e+02
  2.140e+02  3.560e+02  1.100e+02  3.540e+02  3.300e+01  4.050e+02
  8.600e+01  1.520e+02  3.530e+02  2.600e+01  3.200e+01  8.500e+01
  0.000e+00  8.200e+01  9.200e+01  5.500e+01  1.580e+02  6.400e+01
  1.840e+02  2.010e+02  3.280e+02  3.930e+02  6.100e+01  2.670e+02
  1.890e+02  8.300e+01  4.000e+02  3.400e+01  2.030e+02  3.500e+01
  2.800e+02  4.170e+02  1.620e+02  2.370e+02  2.420e+02  2.270e+02
  1.730e+02  1.460e+02  2.430e+02  4.250e+02  1.130e+02  2.600e+02
  3.950e+02  2.660e+02  5.800e+01  4.100e+02  3.880e+02  1.300e+01
  6.200e+01  3.660e+02  3.380e+02  3.340e+02 -1.000e+01  3.780e+02
 -2.000e+00  3.510e+02  3.890e+02  1.600e+01  3.370e+02  1.660e+02
  1.800e+01  1.300e+02  4.300e+01  3.730e+02  4.260e+02  3.960e+02
  4.190e+02  3.770e+02  1.900e+02  3.350e+02  5.200e+01  7.000e+01
  3.110e+02  1.410e+02 -1.000e+00  2.630e+02  2.000e+02  1.440e+02
  3.200e+02  1.900e+01  2.930e+02  2.400e+02  3.000e+02  4.210e+02
  3.320e+02  2.710e+02  1.560e+02  4.200e+02  3.990e+02  1.200e+01
  1.500e+01  1.380e+02  3.270e+02  1.240e+02  1.370e+02  1.920e+02
  8.100e+01  3.610e+02  3.410e+02  2.130e+02  3.360e+02  2.300e+01
  7.800e+01  1.880e+02  6.600e+01  8.000e+01  3.820e+02  3.290e+02
  2.560e+02 -6.000e+00  3.860e+02  1.090e+02  3.190e+02  5.000e+01
  1.180e+02  3.500e+02  1.500e+02  3.130e+02  2.480e+02  2.300e+02
  1.450e+02  4.070e+02  4.220e+02  4.600e+01  1.010e+02  2.100e+02
  1.040e+02  3.230e+02  2.060e+02  2.950e+02  3.970e+02  2.760e+02
  3.980e+02  1.350e+02  4.120e+02  8.700e+01 -9.000e+00  3.150e+02
  1.320e+02  4.200e+01  7.300e+01  1.770e+02  2.450e+02  2.720e+02
  2.470e+02  3.940e+02  1.790e+02  3.100e+01  9.500e+01  1.540e+02
  2.040e+02  3.710e+02  3.120e+02  3.800e+02  2.700e+02  4.500e+01
  1.760e+02  3.790e+02  2.640e+02  4.020e+02  5.300e+01  2.520e+02
  5.000e+00  3.620e+02  2.380e+02  4.140e+02  2.090e+02  4.060e+02
  1.100e+01  2.350e+02  3.180e+02  1.400e+02  1.070e+02  1.310e+02
  1.170e+02  3.160e+02  1.190e+02  4.240e+02  1.550e+02  2.870e+02
  8.400e+01  2.910e+02  2.070e+02  3.490e+02  1.980e+02  1.430e+02
  2.850e+02  3.580e+02  3.310e+02  2.830e+02  1.140e+02  7.700e+01
  3.760e+02  2.110e+02  1.120e+02  2.960e+02  1.810e+02  1.060e+02
  9.700e+01  3.680e+02  2.310e+02  2.970e+02 -4.000e+00  1.990e+02
  1.000e+01  9.400e+01  7.500e+01  1.820e+02  1.640e+02  3.810e+02
  2.530e+02  1.910e+02  7.100e+01  9.800e+01  4.080e+02  1.590e+02
  3.260e+02  1.470e+02  1.860e+02  1.870e+02  2.680e+02  8.800e+01
  4.040e+02  3.690e+02  2.920e+02  1.710e+02  3.010e+02  1.290e+02
  3.000e+01  3.650e+02  2.690e+02  6.700e+01  3.400e+02  6.300e+01
  2.360e+02 -8.000e+00  2.510e+02  3.240e+02  9.300e+01  9.100e+01
  2.590e+02  4.000e+00  3.840e+02  2.650e+02  2.210e+02  1.220e+02
  7.000e+00  2.900e+01  1.160e+02  3.920e+02  1.750e+02  3.030e+02
  2.330e+02  6.900e+01  3.670e+02  2.390e+02  3.600e+01  1.490e+02
  3.900e+01  3.870e+02  3.210e+02  3.020e+02  3.000e+00  1.830e+02
  8.000e+00  2.440e+02  6.000e+01  1.530e+02  3.550e+02  2.500e+02
  3.640e+02 -5.000e+00  2.160e+02  4.180e+02  1.670e+02  1.780e+02
  1.400e+01  3.700e+02  2.540e+02  2.200e+01  3.330e+02  2.400e+01
  2.460e+02  2.610e+02  1.420e+02  2.120e+02  3.390e+02  2.800e+01
  3.090e+02  1.740e+02  2.320e+02  2.000e+01  1.330e+02  1.700e+01
  2.700e+01  4.100e+01  2.260e+02  1.080e+02  1.680e+02  2.550e+02
  2.780e+02  1.250e+02  5.700e+01  1.390e+02  6.500e+01  2.250e+02
  2.050e+02  2.810e+02  2.500e+01  1.950e+02  3.700e+01  2.790e+02
  1.150e+02  2.740e+02  2.150e+02  1.340e+02  6.000e+00  1.940e+02
  1.110e+02  2.170e+02  1.960e+02  2.200e+02  2.180e+02  4.230e+02
  3.300e+02  7.900e+01  1.850e+02  9.000e+01  2.000e+00  2.750e+02
  3.480e+02  3.140e+02  3.100e+02  1.600e+02  3.570e+02  4.400e+01
  3.590e+02  2.990e+02  4.130e+02  2.820e+02  2.900e+02  1.260e+02
  3.800e+01  2.490e+02  2.020e+02  7.200e+01  2.770e+02  2.100e+01
  1.650e+02  7.400e+01  2.220e+02  4.090e+02  1.700e+02  2.410e+02
  8.900e+01  1.280e+02  1.210e+02  2.230e+02  2.730e+02  5.900e+01
  1.230e+02  2.290e+02 -3.000e+00  3.850e+02  3.050e+02  3.070e+02
  9.900e+01  2.340e+02  2.570e+02  3.060e+02  5.100e+01  2.080e+02
  2.840e+02  1.360e+02  3.910e+02  4.900e+01  1.510e+02  1.270e+02
  3.430e+02  3.080e+02  1.480e+02  4.010e+02  3.170e+02  3.040e+02
  1.610e+02  3.600e+02  2.980e+02  4.000e+01  3.630e+02  4.030e+02
  1.570e+02  3.420e+02  2.620e+02  3.900e+02  3.460e+02  1.020e+02
  4.800e+01  1.200e+02  2.880e+02 -7.000e+00  4.150e+02  3.677e+03]

Unique values in 'house_rules':
["Clean up and treat the home the way you'd like your home to be treated.  No smoking."
 'Pet friendly but please confirm with me if the pet you are planning on bringing with you is OK. I have a cute and quiet mixed chihuahua. I could accept more guests (for an extra fee) but this also needs to be confirmed beforehand. Also friends traveling together could sleep in separate beds for an extra fee (the second bed is either a sofa bed or inflatable bed). Smoking is only allowed on the porch.'
 "I encourage you to use my kitchen, cooking and laundry facilities. There is no additional charge to use the washer/dryer in the basement.  No smoking, inside or outside. Come home as late as you want.  If you come home stumbling drunk, it's OK the first time. If you do it again, and you wake up me or the neighbors downstairs, we will be annoyed.  (Just so you know . . . )"
 ...
 '15 nights minimum stay No pets at any time No smoking Please be mindful of the furniture and personal belongings, it was all furnished with designer pieces and hard to replace things.'

In [337]:
df['neighbourhood group'] = df['neighbourhood group'].replace({'manhatan': 'Manhattan', 'brookln': 'Brooklyn'})
print(df['neighbourhood group'].unique())

['Brooklyn' 'Manhattan' 'Queens' 'None' 'Staten Island' 'Bronx']

In [338]:
df['minimum nights'] = pd.to_numeric(df['minimum nights'], errors='coerce')
df['minimum nights'] = df['minimum nights'].clip(lower=1, upper=365)
print(df['minimum nights'])

0         10.0
1         30.0
2          3.0
3         30.0
4         10.0
          ...
102594     1.0
102595     1.0
102596     3.0
102597     2.0
102598     1.0
Name: minimum nights, Length: 102599, dtype: float64

In [339]:
df['availability 365'] = pd.to_numeric(df['availability 365'], errors='coerce')
df['availability 365']=df['availability 365'].clip(lower=0, upper=365)
print(df['availability 365'])

0         286.0
1         228.0
2         352.0
3         322.0
4         289.0
          ...
102594    227.0
102595    365.0
102596    342.0
102597    365.0
102598     69.0
Name: availability 365, Length: 102599, dtype: float64

In [340]:
manhattan_neighborhoods = ['East Harlem', 'Upper East Side', 'Upper West Side', 'Chelsea', 'Greenwich Village', 'Chinatown','East Village', 'Washington Heights', 'Harlem']
brooklyn_neighborhoods = ['Williamsburg', 'Bedford-Stuyvesant', 'Bushwick', 'Bedford', 'Prospect Heights', 'Clinton Hill']
bronx_neighborhoods = ['Eastchester']
queens_neighborhoods = ['Woodside', 'Queens Village']


def neighborhoodgrp(row):
    if row['neighbourhood'] in manhattan_neighborhoods and row['neighbourhood group'] == 'None':
        return 'Manhattan'
    elif row['neighbourhood'] in brooklyn_neighborhoods and row['neighbourhood group'] == 'None':
        return 'Brooklyn'
    elif row['neighbourhood'] in bronx_neighborhoods and row['neighbourhood group'] == 'None':
        return 'Bronx'
    elif row['neighbourhood'] in queens_neighborhoods and row['neighbourhood group'] == 'None':
        return 'Queens'
    return row['neighbourhood group']


df['neighbourhood group'] = df.apply(neighborhoodgrp, axis=1)

In [341]:
df.columns = df.columns.str.strip().str.upper().str.replace(' ', '_')
columns_to_upper = [
    'NAME', 
    'HOST_IDENTITY_VERIFIED', 
    'HOST_NAME', 
    'NEIGHBOURHOOD_GROUP', 
    'NEIGHBOURHOOD', 
    'COUNTRY', 
    'INSTANT_BOOKABLE', 
    'CANCELLATION_POLICY', 
    'ROOM_TYPE', 
    'HOUSE_RULES'
]

for col in columns_to_upper:
    if col in df.columns:
        df[col] = df[col].astype(str).str.strip().str.upper()

In [342]:
print(df)

             ID                                              NAME  \
0       1001254                CLEAN & QUIET APT HOME BY THE PARK
1       1002102                             SKYLIT MIDTOWN CASTLE
2       1002403               THE VILLAGE OF HARLEM....NEW YORK !
3       1002755                                              NONE
4       1003689  ENTIRE APT: SPACIOUS STUDIO/LOFT BY CENTRAL PARK
...         ...                                               ...
102594  6092437                        SPARE ROOM IN WILLIAMSBURG
102595  6092990                     BEST LOCATION NEAR COLUMBIA U
102596  6093542                    COMFY, BRIGHT ROOM IN BROOKLYN
102597  6094094                  BIG STUDIO-ONE STOP FROM MIDTOWN
102598  6094647                              585 SF LUXURY STUDIO

            HOST_ID HOST_IDENTITY_VERIFIED    HOST_NAME NEIGHBOURHOOD_GROUP  \
0       80014485718            UNCONFIRMED     MADALINE            BROOKLYN
1       52335172823               VERIFIED        JENNA           MANHATTAN
2       78829239556            UNCONFIRMED        ELISE           MANHATTAN
3       85098326012            UNCONFIRMED        GARRY            BROOKLYN
4       92037596077               VERIFIED       LYNDON           MANHATTAN
...             ...                    ...          ...                 ...
102594  12312296767               VERIFIED         KRIK            BROOKLYN
102595  77864383453            UNCONFIRMED        MIFAN           MANHATTAN
102596  69050334417            UNCONFIRMED        MEGAN            BROOKLYN
102597  11160591270            UNCONFIRMED  CHRISTOPHER              QUEENS
102598  68170633372            UNCONFIRMED      REBECCA           MANHATTAN

              NEIGHBOURHOOD       LAT      LONG        COUNTRY  ...  \
0                KENSINGTON  40.64749 -73.97237  UNITED STATES  ...
1                   MIDTOWN  40.75362 -73.98377  UNITED STATES  ...
2                    HARLEM  40.80902 -73.94190  UNITED STATES  ...
3              CLINTON HILL  40.68514 -73.95976  UNITED STATES  ...
4               EAST HARLEM  40.79851 -73.94399  UNITED STATES  ...
...                     ...       ...       ...            ...  ...
102594         WILLIAMSBURG  40.70862 -73.94651  UNITED STATES  ...
102595  MORNINGSIDE HEIGHTS  40.80460 -73.96545  UNITED STATES  ...
102596           PARK SLOPE  40.67505 -73.98045  UNITED STATES  ...
102597     LONG ISLAND CITY  40.74989 -73.93777  UNITED STATES  ...
102598      UPPER WEST SIDE  40.76807 -73.98342  UNITED STATES  ...

       SERVICE_FEE MINIMUM_NIGHTS NUMBER_OF_REVIEWS REVIEWS_PER_MONTH  \
0            193.0           10.0               9.0              0.21
1             28.0           30.0              45.0              0.38
2            124.0            3.0               0.0              0.00
3             74.0           30.0             270.0              4.64
4             41.0           10.0               9.0              0.10
...            ...            ...               ...               ...
102594       169.0            1.0               0.0              0.00
102595       167.0            1.0               1.0              0.02
102596       198.0            3.0               0.0              0.00
102597       109.0            2.0               5.0              0.10
102598       206.0            1.0               0.0              0.00

        REVIEW_RATE_NUMBER  CALCULATED_HOST_LISTINGS_COUNT  AVAILABILITY_365  \
0                      4.0                             6.0             286.0
1                      4.0                             2.0             228.0
2                      5.0                             1.0             352.0
3                      4.0                             1.0             322.0
4                      3.0                             1.0             289.0
...                    ...                             ...               ...
102594                 3.0                             1.0             227.0
102595                 2.0                             2.0             365.0
102596                 5.0                             1.0             342.0
102597                 3.0                             1.0             365.0
102598                 3.0                             1.0              69.0

                                              HOUSE_RULES  YEAR_REVIEW  \
0       CLEAN UP AND TREAT THE HOME THE WAY YOU'D LIKE...         2021
1       PET FRIENDLY BUT PLEASE CONFIRM WITH ME IF THE...         2022
2       I ENCOURAGE YOU TO USE MY KITCHEN, COOKING AND...            0
3                                                    NONE         2019
4       PLEASE NO SMOKING IN THE HOUSE, PORCH OR ON TH...         2018
...                                                   ...          ...
102594  NO SMOKING NO PARTIES OR EVENTS OF ANY KIND PL...            0
102595  HOUSE RULES: GUESTS AGREE TO THE FOLLOWING TER...         2015
102596                                               NONE            0
102597                                               NONE         2015
102598                                               NONE            0

        MONTH_REVIEW
0                 10
1                  5
2                  0
3                  7
4                 11
...              ...
102594             0
102595             7
102596             0
102597            10
102598             0

[102599 rows x 25 columns]

In [343]:
df.to_csv('Airbnb_Cleaned.csv', index=False)